AWSTemplateFormatVersion: '2010-09-09'
Description: EKS multi-cluster 
Parameters:
  EKSIAMRoleName:
    Type: String
    Description: Name of EKS Role 
    Default: EKSMultiClusterRole
  EKSMultiClusterName:
    Type: String
    Description: Name of EKS Cluster 
    Default: multi-cluster
  VPCCidrBlock:
    Type: String
    Description: VPC Block Size 
    Default: 10.0.0.0/16
  VPCSubnetBlock1:
    Type: String
    Default: 10.0.1.0/24
    Description: CidrBlock for public subnet 01 within the VPC
  VPCSubnetBlock2:
    Type: String
    Default: 10.0.2.0/24
    Description: CidrBlock for public subnet 01 within the VPC
  VPCSubnetBlock3:
    Type: String
    Default: 10.0.3.0/24
    Description: CidrBlock for public subnet 01 within the VPC
  VPCSubnetBlock4:
    Type: String
    Default: 10.0.4.0/24
    Description: CidrBlock for public subnet 01 within the VPC
Resources:
  #============================================================================#
  # Role
  #============================================================================#
  MultiClusterRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Ref EKSIAMRoleName
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
            - Effect: Allow
              Principal:
                Service:
                  - eks.amazonaws.com
              Action:
                - 'sts:AssumeRole'
      Description: EKS Administrator Role for EKS multi-cluster
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  #============================================================================#
  # VPC
  #============================================================================#
  MultiClusterVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock
  #============================================================================#
  # Subnet
  #============================================================================#
  MultiClusterSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MultiClusterVPC
      CidrBlock: !Ref VPCSubnetBlock1
      AvailabilityZone: !Select [ 0, !GetAZs ]
    DependsOn: 
      - MultiClusterVPC
  MultiClusterSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MultiClusterVPC
      CidrBlock: !Ref VPCSubnetBlock2
      AvailabilityZone: !Select [ 1, !GetAZs ]
    DependsOn: 
      - MultiClusterVPC
  MultiClusterSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MultiClusterVPC
      CidrBlock: !Ref VPCSubnetBlock3
      AvailabilityZone: !Select [ 0, !GetAZs ]
    DependsOn: 
      - MultiClusterVPC
  MultiClusterSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MultiClusterVPC
      CidrBlock: !Ref VPCSubnetBlock4
      AvailabilityZone: !Select [ 1, !GetAZs ]
    DependsOn: 
      - MultiClusterVPC
  #============================================================================#
  # Security Group
  #============================================================================#
  MultiClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref MultiClusterVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 6379
    DependsOn: 
      - MultiClusterVPC
  #============================================================================#
  # EKS Cluster
  #============================================================================#
  MultiClusterEKS:
    Type: AWS::EKS::Cluster
    Properties: 
      Name: !Ref EKSMultiClusterName 
      RoleArn:  !GetAtt MultiClusterRole.Arn
      ResourcesVpcConfig:
          SecurityGroupIds:
          - !Ref MultiClusterSecurityGroup
          SubnetIds:
          - !Ref MultiClusterSubnet1
          - !Ref MultiClusterSubnet2
          - !Ref MultiClusterSubnet3
          - !Ref MultiClusterSubnet4
    DependsOn: 
      - MultiClusterRole
      - MultiClusterSubnet1
      - MultiClusterSubnet2
      - MultiClusterSubnet3
      - MultiClusterSubnet4
      - MultiClusterSecurityGroup